### ISSUE TITLE
Enhancement: Implement question type contract

### ISSUE THREAD

**Issue by otacke** [jithin-space/h5p-image-pair#3]
Hi!

I really love the look and feel of image pairing! Had a quick glance at the code, and it seems you're not implementing the [question type contract](https://h5p.org/documentation/developers/contracts). Since people will probably ask to include your content type in QuestionSet and Columns, would you consider to change the code whenever you have some time?

Just let me know if I should just do it myself and create a pull request ;-)

Best,
Oliver

**Comment by jithin-space** [comment]
Hi otacke,
Glad that you liked it. I am ready to improve the content type so that it can more useful. But I don't know how long it will take me to make the updation. If the implementation you requested is  urgent, I am happy to get more developers involved in contributing to the content type :)

**Comment by otacke** [comment]
Hi Jithin!

It's not urgent. Just foresight ;-) Some people have been asking me if QuestionSet would contain H5P Dictation although it has not even been released yet.

Best,
Oliver

**Comment by jithin-space** [comment]
Ok, Then I will be happy to make the implementation myself :)
